In [17]:
import pandas as pd


def divided_differences_table(nodes, f=None, values=None):
    n = len(nodes)
    table = [[0 for _ in range(n + 1)] for _ in range(n)]

    if values is not None and len(values) != n:
        raise ValueError("'values' must have the same length as 'nodes'.")

    if f is None and values is None:
        raise ValueError("Provide either a function 'f' or a list 'values'.")

    # Column 0: x values
    for i in range(n):
        table[i][0] = nodes[i]

    # Column 1: f(x)
    for i in range(n):
        if values is not None:
            table[i][1] = values[i]
        else:
            table[i][1] = f(nodes[i])

    # Columns 2..n: divided differences
    # table[i][j] corresponds to f[x_i, ..., x_{i + j - 1}]
    for j in range(2, n + 1):
        for i in range(0, n - j + 1):
            numerator = table[i + 1][j - 1] - table[i][j - 1]
            denominator = nodes[i + j - 1] - nodes[i]
            table[i][j] = numerator / denominator

    columns = ["x", "f(x)"] + [f"order_{k}" for k in range(1, n)]
    return pd.DataFrame(table, columns=columns)


nodes = [0, 1, 2]
f = lambda x: 1 / (1 + x)

print("Exercise 1 a)")
dd_table = divided_differences_table(nodes, f)
dd_table

Exercise 1 a)

   x      f(x)   order_1   order_2
0  0  1.000000 -0.500000  0.166667
1  1  0.500000 -0.166667  0.000000
2  2  0.333333  0.000000  0.000000

In [12]:
import pandas as pd


def divided_differences_double_nodes(nodes, f, df):
    """
    Divided differences table for double nodes (Hermite interpolation).
    Each node x_i is repeated twice.

    Parameters:
        nodes: [x0, x1, ..., xn]
        f:    function f(x)
        df:   derivative f'(x)
    """
    n = len(nodes)
    m = 2 * n  # number of rows after doubling nodes

    z = [0.0] * m
    table = [[0 for _ in range(m + 1)] for _ in range(m)]

    # Build doubled nodes and first two columns
    for i in range(n):
        z[2 * i] = nodes[i]
        z[2 * i + 1] = nodes[i]

        table[2 * i][0] = z[2 * i]
        table[2 * i + 1][0] = z[2 * i + 1]

        table[2 * i][1] = f(nodes[i])
        table[2 * i + 1][1] = f(nodes[i])

    # First-order divided differences:
    # - use derivative only for division-by-zero case (repeated node)
    # - otherwise use the standard formula
    for i in range(m - 1):
        denominator = z[i + 1] - z[i]
        if denominator == 0:
            table[i][2] = df(z[i])
        else:
            table[i][2] = (table[i + 1][1] - table[i][1]) / denominator

    # Higher-order divided differences
    for j in range(3, m + 1):
        for i in range(0, m - j + 1):
            numerator = table[i + 1][j - 1] - table[i][j - 1]
            denominator = z[i + j - 1] - z[i]
            table[i][j] = numerator / denominator

    columns = ["z", "f(z)"] + [f"order_{k}" for k in range(1, m)]
    return pd.DataFrame(table, columns=columns)


# Example usage:
nodes = [0, 1, 2]
f = lambda x: 1 / (1 + x)
df = lambda x: -1 / (1 + x)**2

print("Exercise 1 b)")
hermite_table = divided_differences_double_nodes(nodes, f, df)
hermite_table

Exercise 1 b)

   z      f(z)   order_1   order_2   order_3   order_4   order_5
0  0  1.000000 -1.000000  0.500000 -0.250000  0.083333 -0.027778
1  0  1.000000 -0.500000  0.250000 -0.083333  0.027778  0.000000
2  1  0.500000 -0.250000  0.083333 -0.027778  0.000000  0.000000
3  1  0.500000 -0.166667  0.055556  0.000000  0.000000  0.000000
4  2  0.333333 -0.111111  0.000000  0.000000  0.000000  0.000000
5  2  0.333333  0.000000  0.000000  0.000000  0.000000  0.000000

In [15]:
# Exercise 1 c)
import numpy as np

# 11 equidistant nodes in [1, 2]
nodes = np.linspace(1, 2, 11)
print("Exercise 1 c) - 11 equidistant nodes in [1, 2]")

print("Divided differences table")
dd_table = divided_differences_table(nodes, f)
dd_table

Exercise 1 c) - 11 equidistant nodes in [1, 2]
Divided differences table

,x,f(x),order_1,order_2,order_3,order_4,order_5,order_6,order_7,order_8,order_9,order_10
0,1.0,0.500000,-0.238095,0.108225,-0.047054,0.019606,-0.007842,0.003016,-0.001117,0.000399,-0.000138,0.000046
1,1.1,0.476190,-0.216450,0.094109,-0.039212,0.015685,-0.006033,0.002234,-0.000798,0.000275,-0.000092,0.000000
2,1.2,0.454545,-0.197628,0.082345,-0.032938,0.012668,-0.004692,0.001676,-0.000578,0.000193,0.000000,0.000000
3,1.3,0.434783,-0.181159,0.072464,-0.027871,0.010322,-0.003687,0.001271,-0.000424,0.000000,0.000000,0.000000
4,1.4,0.416667,-0.166667,0.064103,-0.023742,0.008479,-0.002924,0.000975,0.000000,0.000000,0.000000,0.000000
5,1.5,0.400000,-0.153846,0.056980,-0.020350,0.007017,-0.002339,0.000000,0.000000,0.000000,0.000000,0.000000
6,1.6,0.384615,-0.142450,0.050875,-0.017543,0.005848,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,1.7,0.370370,-0.132275,0.045612,-0.015204,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,1.8,0.357143,-0.123153,0.041051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,1.9,0.344828,-0.114943,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,2.0,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [16]:
print("Hermite table")
hermite_table = divided_differences_double_nodes(nodes, f, df)
hermite_table

Hermite table

,z,f(z),order_1,order_2,order_3,order_4,order_5,order_6,order_7,order_8,...,order_12,order_13,order_14,order_15,order_16,order_17,order_18,order_19,order_20,order_21
0,1.0,0.500000,-0.250000,0.119048,-0.056689,0.025768,-0.011713,0.005092,-0.002214,0.000923,...,0.000024,-0.000009,3.591778e-06,-1.189965e-06,-7.738179e-07,0.000005,-0.000014,0.000035,-0.000069,0.000132
1,1.0,0.500000,-0.238095,0.113379,-0.051536,0.023425,-0.010185,0.004428,-0.001845,0.000769,...,0.000018,-0.000007,2.758803e-06,-1.809019e-06,3.301234e-06,-0.000007,0.000018,-0.000034,0.000063,0.000000
2,1.1,0.476190,-0.226757,0.103072,-0.046851,0.020370,-0.008856,0.003690,-0.001538,0.000615,...,0.000013,-0.000005,1.311587e-06,8.319680e-07,-3.339016e-06,0.000009,-0.000016,0.000029,0.000000,0.000000
3,1.1,0.476190,-0.216450,0.098386,-0.042777,0.018599,-0.007749,0.003229,-0.001292,0.000517,...,0.000011,-0.000004,1.893965e-06,-1.839245e-06,3.473330e-06,-0.000006,0.000010,0.000000,0.000000,0.000000
4,1.2,0.454545,-0.206612,0.089831,-0.039057,0.016274,-0.006781,0.002712,-0.001085,0.000417,...,0.000008,-0.000003,4.225687e-07,9.394192e-07,-2.037268e-06,0.000003,0.000000,0.000000,0.000000,0.000000
5,1.2,0.454545,-0.197628,0.085925,-0.035802,0.014918,-0.005967,0.002387,-0.000918,0.000353,...,0.000006,-0.000002,1.080162e-06,-6.903950e-07,3.131188e-08,0.000000,0.000000,0.000000,0.000000,0.000000
6,1.3,0.434783,-0.189036,0.078765,-0.032819,0.013127,-0.005251,0.002020,-0.000777,0.000288,...,0.000005,-0.000002,5.278461e-07,-6.653455e-07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
7,1.3,0.434783,-0.181159,0.075483,-0.030193,0.012077,-0.004645,0.001787,-0.000662,0.000245,...,0.000004,-0.000001,6.210419e-08,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
8,1.4,0.416667,-0.173611,0.069444,-0.027778,0.010684,-0.004109,0.001522,-0.000564,0.000201,...,0.000003,-0.000001,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
9,1.4,0.416667,-0.166667,0.066667,-0.025641,0.009862,-0.003653,0.001353,-0.000483,0.000173,...,0.000002,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
10,1.5,0.400000,-0.160000,0.061538,-0.023669,0.008766,-0.003247,0.001160,-0.000414,0.000143,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
11,1.5,0.400000,-0.153846,0.059172,-0.021915,0.008117,-0.002899,0.001035,-0.000357,0.000123,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
12,1.6,0.384615,-0.147929,0.054789,-0.020292,0.007247,-0.002588,0.000893,-0.000308,0.000103,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
13,1.6,0.384615,-0.142450,0.052759,-0.018843,0.006730,-0.002321,0.000800,-0.000267,0.000089,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
14,1.7,0.370370,-0.137174,0.048991,-0.017497,0.006033,-0.002080,0.000693,-0.000231,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
15,1.7,0.370370,-0.132275,0.047241,-0.016290,0.005617,-0.001872,0.000624,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
16,1.8,0.357143,-0.127551,0.043983,-0.015167,0.005056,-0.001685,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
17,1.8,0.357143,-0.123153,0.042466,-0.014155,0.004718,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
18,1.9,0.344828,-0.118906,0.039635,-0.013212,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
19,1.9,0.344828,-0.114943,0.038314,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
20,2.0,0.333333,-0.111111,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
21,2.0,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000

In [18]:
# Exercise 2
# Given nodes = [-2, -1, 0, 1, 2, 3, 4]
# and values for f(x) = [-5, 1, 1, 1, 7, 25, 60]

# a) Construct the divided differences table of the data
nodes_ex2 = [-2, -1, 0, 1, 2, 3, 4]
values_ex2 = [-5, 1, 1, 1, 7, 25, 60]

print("Exercise 2 a)")
ex2_table = divided_differences_table(nodes_ex2, values=values_ex2)
ex2_table

Exercise 2 a)

   x  f(x)  order_1  order_2   order_3   order_4   order_5   order_6
0 -2    -5      6.0     -3.0  1.000000  0.000000  0.000000 -0.001389
1 -1     1      0.0      0.0  1.000000  0.000000 -0.008333  0.000000
2  0     1      0.0      3.0  1.000000 -0.041667  0.000000  0.000000
3  1     1      6.0      6.0  0.833333  0.000000  0.000000  0.000000
4  2     7     18.0      8.5  0.000000  0.000000  0.000000  0.000000
5  3    25     35.0      0.0  0.000000  0.000000  0.000000  0.000000
6  4    60      0.0      0.0  0.000000  0.000000  0.000000  0.000000

In [25]:
import pandas as pd


def finite_differences_table(nodes, values, mode="forward"):
    """
    Build finite differences table from tabulated values.

    mode:
        - "forward" (default)
        - "backward"
        - "simple" (alias of forward)
    """
    if len(nodes) != len(values):
        raise ValueError("'nodes' and 'values' must have the same length.")

    mode = mode.lower()
    if mode == "simple":
        mode = "forward"
    if mode not in {"forward", "backward"}:
        raise ValueError("mode must be 'forward', 'backward', or 'simple'.")

    n = len(values)
    table = [[0 for _ in range(n + 1)] for _ in range(n)]

    # Base columns
    for i in range(n):
        table[i][0] = nodes[i]
        table[i][1] = values[i]

    prev = values[:]
    for order in range(1, n):
        if mode == "forward":
            curr = [prev[i + 1] - prev[i] for i in range(len(prev) - 1)]
        else:  # backward
            curr = [prev[i] - prev[i - 1] for i in range(1, len(prev))]

        for i, val in enumerate(curr):
            if mode == "forward":
                # Forward differences are aligned at the top.
                row = i
            else:
                # Backward differences are aligned at the bottom.
                row = i + order
            table[row][order + 1] = val

        prev = curr

    columns = ["x", "f(x)"] + [f"delta_{k}" for k in range(1, n)]
    return pd.DataFrame(table, columns=columns)


print("Exercise 2 b) - Forward differences")
forward_table_ex2 = finite_differences_table(nodes_ex2, values_ex2, mode="forward")
forward_table_ex2

Exercise 2 b) - Forward differences

   x  f(x)  delta_1  delta_2  delta_3  delta_4  delta_5  delta_6
0 -2    -5        6       -6        6        0        0       -1
1 -1     1        0        0        6        0       -1        0
2  0     1        0        6        6       -1        0        0
3  1     1        6       12        5        0        0        0
4  2     7       18       17        0        0        0        0
5  3    25       35        0        0        0        0        0
6  4    60        0        0        0        0        0        0

In [26]:
# Exercise 2 c)
# Backward differences
backward_table_ex2 = finite_differences_table(nodes_ex2, values_ex2, mode="backward")
backward_table_ex2

   x  f(x)  delta_1  delta_2  delta_3  delta_4  delta_5  delta_6
0 -2    -5        0        0        0        0        0        0
1 -1     1        6        0        0        0        0        0
2  0     1        0       -6        0        0        0        0
3  1     1        0        0        6        0        0        0
4  2     7        6        6        6        0        0        0
5  3    25       18       12        6        0        0        0
6  4    60       35       17        5       -1       -1       -1